name: eunbeyol
description: For my lovely girlfriend

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^6.0.0
  flutter_svg: ^0.22.0
  http: ^0.13.3
  flutter_spinkit: ^5.1.0
  drop_cap_text: ^1.1.3

  webview_flutter:
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
